# Site settings
title: Russell Tran blog
description: "AI Security Engineer"
url: "https://russell-tran.github.io"
github_username: Russell-Tran

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
